# Generated by Django 3.1.7 on 2021-04-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limbo', '0003_auto_20210329_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('remarks', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='schedule',
            name='iid',
            field=models.CharField(max_length=50),
        ),
    ]
