# Generated by Django 3.1.7 on 2021-04-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limbo', '0005_duelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelAllot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=50, unique=True)),
                ('room', models.CharField(max_length=50)),
            ],
        ),
    ]
